logging:
  level:
    root: INFO
    io:
      github:
        hirannor:
          oms: DEBUG

  file:
    path: logs

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5342/hexagondb
    username: root
    password: hexagonal123
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: hexagonal-ddd-app

adapter:
  authentication: jwt
  persistence: spring-data-jpa
  payment: stripe
  notification: email
  messaging: rabbitmq
  web: rest

payment:
  stripe:
    api-key: sk_test_
    webhook-secret: whsec_
    success-url: http://google.com
    failure-url: http://google.com

email:
  from: no-reply@yourapp.com

security:
  jwt:
    # Secret key used for signing and verifying JWTs.
    # Must be a Base64-encoded random string, at least 256 bits (32 bytes) long for HS256.
    # Example: generate with `openssl rand -base64 32`
    secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbb==
    algorithm: HS256
    access-expiration: 30m
    refresh-expiration: 30d
    issuer: oms-backend
    audience: oms-clients

messaging:
  rabbit:
    exchange: oms.exchange
    queue: oms.queue
    dlq: oms.queue.dlq
    dlx: oms.exchange.dlx
    outbox:
      poll-interval: 5s
      batch-size: 50
    retry:
      max-attempts: 3

outbox:
  house-keeping-cron:  "0 0 2 * * *"