logging:
  level:
    root: INFO
  file:
    path: logs

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5342/hexagondb
    username: root
    password: hexagonal123
    hikari:
      auto-commit: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
    hibernate:
      ddl-auto: validate
  application:
    name: hexagonal-ddd-app

adapter:
  authentication: jwt
  persistence: spring-data-jpa
  payment: stripe
  notification: email
  messaging: spring-event-bus
  web: rest

payment:
  stripe:
    api-key: API_KEY
    webhook-secret: whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    success-url: success_url
    failure-url: failure_url