logging:
  level:
    root: INFO
  file:
    path: logs

spring:
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5342/hexagondb
    username: root
    password: hexagonal123
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: hexagonal-ddd-app

adapter:
  authentication: jwt
  persistence: spring-data-jpa
  payment: stripe
  notification: email
  messaging: spring-event-bus
  web: rest

payment:
  stripe:
    api-key: sk_test_
    webhook-secret: whsec_
    success-url: http://google.com
    failure-url: http://google.com

email:
  from: no-reply@yourapp.com

security:
  jwt:
    secret: Xq8y7u4y6j7s9aVn7xDk0JZ4k1vHz3oZlwjrXbVZpCk=