export enum OrderStatus {
  CREATED = 'CREATED',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  CANCELLED = 'CANCELLED',
  DELIVERED = 'DELIVERED',
  PAID_SUCCESSFULLY = 'PAID_SUCCESSFULLY',
  PAYMENT_FAILED = 'PAYMENT_FAILED'

}
