name: Full Stack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Build & Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: oms-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & test with Maven
        run: mvn --batch-mode --update-snapshots verify

  frontend:
    name: Frontend Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: oms-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: oms-frontend/package-lock.json

      - name: Upgrade npm to match local
        run: npm install -g npm@11

      - name: Print Node & npm versions
        run: |
          node -v
          npm -v

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Check dependency tree
        run: npm ls --depth=0 || true

      - name: Install dependencies
        run: npm ci

      - name: Generate API clients
        run: npm run generate:apis

      - name: Lint & Build
        run: |
          npm run lint
          npm run build --if-present
