openapi: 3.0.3
info:
  title: Customers API
  description: Customers API
  version: 1.0.0
security:
  - bearerAuth: [ ]
paths:
  /customers/me:
    get:
      summary: Retrieves the current logged-in customer
      security:
        - bearerAuth: [ ]
      description: Fetches the customer corresponding to the current authenticated user.
      operationId: authenticatedCustomer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /customers:
    get:
      summary: Retrieves all customer
      security:
        - bearerAuth: [ ]
      description: Retrieves all customer
      operationId: displayAll
      parameters:
        - name: birthDateFrom
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: birthDateTo
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: gender
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Gender'
        - name: emailAddress
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /customers/{customerId}:
    get:
      summary: Retrieves customer by id
      security:
        - bearerAuth: [ ]
      description: Retrieves customer by id
      operationId: displayBy
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      summary: Deletes a customer by id
      security:
        - bearerAuth: [ ]
      description: Deletes a customer by id
      operationId: deleteBy
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful operation
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    patch:
      summary: Change customer personal details
      security:
        - bearerAuth: [ ]
      description: Change customer personal details
      operationId: changePersonalDetails
      requestBody:
        description: Changed customer details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePersonalDetails'
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic
  schemas:
    ChangePersonalDetails:
      type: object
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Digweed
        birthDate:
          type: string
          format: date
          example: 1990-01-01
        address:
          $ref: '#/components/schemas/Address'
        gender:
          $ref: '#/components/schemas/Gender'
    Customer:
      type: object
      properties:
        customerId:
          type: string
          example: f8ba9856-29ca-4611-89c3-a2711be08994
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Digweed
        birthDate:
          type: string
          format: date
          example: 1990-01-01
        address:
          $ref: '#/components/schemas/Address'
        gender:
          $ref: '#/components/schemas/Gender'
        emailAddress:
          type: string
          example: test@test.com
    Address:
      type: object
      required:
        - country
        - postalCode
        - city
        - streetAddress
      properties:
        country:
          $ref: '#/components/schemas/Country'
        city:
          type: string
          example: Budapest
        postalCode:
          type: integer
          example: 1007
        streetAddress:
          type: string
          example: Wolf street
    ProblemDetails:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
        fields:
          type: object
          additionalProperties:
            type: string
          description: A map of fieldName -> validation error message
    Country:
      type: string
      enum:
        - HUNGARY
        - GERMANY
      example: HUNGARY
    Gender:
      type: string
      enum:
        - MALE
        - FEMALE
      example: MALE